### ISSUE TITLE
Error with `(4) Setup Docker images`

### ISSUE THREAD

**Issue by zhangysh1995** [DBCobra/CobraBench#1]
Got an error with the following command:

``
fab -r eval/fabfile.py -H localhost install-docker --uname="zhangys"
``

````
(txn) zhangys@191host033:~/CobraHome/CobraBench$ fab -r eval/fabfile.py -H localhost install-docker --uname="zhangys"
Traceback (most recent call last):
  File "/home/zhangys/local/anaconda3/envs/txn/bin/fab", line 8, in <module>
    sys.exit(program.run())
  File "/home/zhangys/local/anaconda3/envs/txn/lib/python3.7/site-packages/invoke/program.py", line 363, in run
    self.execute()
  File "/home/zhangys/local/anaconda3/envs/txn/lib/python3.7/site-packages/invoke/program.py", line 532, in execute
    executor.execute(*self.tasks)
  File "/home/zhangys/local/anaconda3/envs/txn/lib/python3.7/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/zhangys/local/anaconda3/envs/txn/lib/python3.7/site-packages/invoke/tasks.py", line 128, in __call__
    result = self.body(*args, **kwargs)
  File "/home/zhangys/CobraHome/CobraBench/eval/fabfile.py", line 15, in install_docker
    conn.run('curl -fsSL https://get.docker.com -o get-docker.sh')
  File "<decorator-gen-3>", line 2, in run
  File "/home/zhangys/local/anaconda3/envs/txn/lib/python3.7/site-packages/fabric/connection.py", line 29, in opens
    self.open()
  File "/home/zhangys/local/anaconda3/envs/txn/lib/python3.7/site-packages/fabric/connection.py", line 615, in open
    self.client.connect(**kwargs)
  File "/home/zhangys/local/anaconda3/envs/txn/lib/python3.7/site-packages/paramiko/client.py", line 437, in connect
    passphrase,
  File "/home/zhangys/local/anaconda3/envs/txn/lib/python3.7/site-packages/paramiko/client.py", line 749, in _auth
    raise saved_exception
  File "/home/zhangys/local/anaconda3/envs/txn/lib/python3.7/site-packages/paramiko/client.py", line 720, in _auth
    filename, pkey_class, passphrase
  File "/home/zhangys/local/anaconda3/envs/txn/lib/python3.7/site-packages/paramiko/client.py", line 571, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/zhangys/local/anaconda3/envs/txn/lib/python3.7/site-packages/paramiko/pkey.py", line 206, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/zhangys/local/anaconda3/envs/txn/lib/python3.7/site-packages/paramiko/rsakey.py", line 55, in __init__
    self._from_private_key_file(filename, password)
  File "/home/zhangys/local/anaconda3/envs/txn/lib/python3.7/site-packages/paramiko/rsakey.py", line 175, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
  File "/home/zhangys/local/anaconda3/envs/txn/lib/python3.7/site-packages/paramiko/pkey.py", line 279, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/home/zhangys/local/anaconda3/envs/txn/lib/python3.7/site-packages/paramiko/pkey.py", line 289, in _read_private_key
    raise SSHException("not a valid " + tag + " private key file")
paramiko.ssh_exception.SSHException: not a valid RSA private key file
````

I could do login without error on both `client1` and `localhost`:
````
(txn) zhangys@191host033:~/CobraHome/CobraBench$ ssh localhost
Linux 191host033 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Mar  5 17:24:07 2021 from ::1

zhangys@191host033:~$ ssh zhangys@xxx
Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-72-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Mar  5 09:34:09 UTC 2021
...
````

I have checked `~/.ssh/config`, and the RSA file path is correct. 
Do you have any idea how this should be fixed? Thank you :)

**Comment by naizhengtan** [comment]
@zcgeng , can you take a look at this? I think the problem is that `fabfile.py` cannot find the correct rsa key, whereas `ssh` can find it.
